# Generated by Django 6.0.6 on 2026-06-09 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., "2025 Launching"', max_length=255)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_pledged', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_fulfilled', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('guest_form', 'Guest Form'), ('member_hub', 'Member Hub'), ('live_log', 'Live Log (Usher)')], default='guest_form', max_length=50)),
                ('recorder_id', models.CharField(blank=True, help_text='ID or name of the usher who recorded this', max_length=100, null=True)),
                ('proof_url', models.URLField(blank=True, null=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
