# Generated by Django 6.0.6 on 2026-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
