# Generated by Django 6.0.6 on 2026-06-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_contribution_is_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parishioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
