# Generated by Django 6.0.6 on 2026-06-10 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_parishioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishioner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='source',
            field=models.CharField(choices=[('registry', 'Registry'), ('manual', 'Manual')], default='registry', max_length=20),
        ),
    ]
