# Generated by Django 6.0.6 on 2026-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_parishioner_created_at_parishioner_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishioner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
