# Generated by Django 6.0.6 on 2026-06-14 16:50

from django.db import migrations


def set_approved(apps, schema_editor):
    Contribution = apps.get_model('contributions', 'Contribution')
    Contribution.objects.all().update(status='approved')

class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_contribution_status'),
    ]

    operations = [
        migrations.RunPython(set_approved, reverse_code=migrations.RunPython.noop),
    ]
