# Generated by Django 6.0.6 on 2026-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_auto_20260614_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
