# Generated by Django 6.0.6 on 2026-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_inflowcategory_contribution_inflow_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflowcategory',
            name='api_key_name',
            field=models.CharField(blank=True, help_text='e.g. PAYSTACK_SECRET_KEY_LAUNCHING (Leave blank for default)', max_length=100, null=True),
        ),
    ]
