# Generated by Django 6.0.6 on 2026-06-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_kids_leaderboard', models.BooleanField(default=False, help_text='Tick this to display the Kids / Children category on the public leaderboard. Leave unticked to show Youth Ambassadors only (recommended until kids data is available).', verbose_name='Show Kids Harvest leaderboard')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
