# Generated by Django 6.0.6 on 2026-06-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contestant_title',
            field=models.CharField(choices=[('Mr CYON Felele', 'Mr CYON Felele'), ('Miss CYON Felele', 'Miss CYON Felele'), ('None', 'Not Contesting')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
