# Generated by Django 6.0.6 on 2026-06-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_contestant_title_member_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
