# Generated by Django 6.0.6 on 2026-06-22 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_has_completed_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('member', 'Member / Contestant'), ('usher', 'Usher / Recorder'), ('approver', 'Approver / Auditor'), ('admin', 'Admin')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='PinResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField(default=False)),
                ('temp_pin', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_resets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
