# Generated by Django 6.0.6 on 2026-06-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_role_pinresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contestant_title',
            field=models.CharField(choices=[('Most Influential Youth Fundraiser (Male)', 'Most Influential Youth Fundraiser (Male)'), ('Most Influential Youth Fundraiser (Female)', 'Most Influential Youth Fundraiser (Female)'), ('Master Harvest', 'Master Harvest'), ('Miss Harvest', 'Miss Harvest'), ('None', 'Not Contesting')], default='None', max_length=50),
        ),
    ]
