# Generated by Django 6.0.6 on 2026-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_member_contestant_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='custom_flyer',
            field=models.ImageField(blank=True, help_text='Optional custom flyer for sharing', null=True, upload_to='flyers/'),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='contestant_title',
            field=models.CharField(choices=[('Most Influential Youth Fundraiser', 'Most Influential Youth Fundraiser'), ('Master Harvest', 'Master Harvest'), ('Miss Harvest', 'Miss Harvest'), ('None', 'Not Contesting')], default='None', max_length=50),
        ),
    ]
