# Generated by Django 6.0.6 on 2026-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_admintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_flyer_locked',
            field=models.BooleanField(default=False, help_text='Lock flyer and profile picture modification/regeneration on dashboard'),
        ),
    ]
